# -*- coding: utf-8 -*-
"""Imersão dados com Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdWDtrfTncwP2QteBvDFsUyClWaA1r7L
"""

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

df.head()

df.info()

df.describe()

df.shape

linhas, colunas = df.shape[0], df.shape[1]

print("Linhas:", linhas)
print("Colunas:", colunas)

df.columns

df["experience_level"].value_counts()

df["employment_type"].value_counts()

df["remote_ratio"].value_counts()

df["company_size"].value_counts()

df.head()

df.describe(include="object")

df.isnull()

df.head()

df.isnull().sum()

df["work_year"].unique()

df[df.isnull().any(axis=1)]

import numpy as np
df_salarios = pd.DataFrame({
    "nome": ["Ana", "Luis", "Betania", "Carlos", "Lucia"],
    "salario": [4000, np.nan, 5000, np.nan, 100000]
})

#calcula a media e substitui os nulos, arredondando.
df_salarios["salario_medias"] = df_salarios["salario"].fillna(df_salarios["salario"].mean().round(2))
'''calcula a mediana e substitui os nulos pela mediana'''
df_salarios["salario_mediana"] = df_salarios["salario"].fillna(df_salarios["salario"].median())
df_salarios

df_temperaturas = pd.DataFrame({
    "Dia da semana": ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta'],
    'Temperatura':[30, np.nan, np.nan, 28, 27]
})
df_temperaturas['Preenchido_bfill'] = df_temperaturas['Temperatura'].bfill()
df_temperaturas

df_cidades = pd.DataFrame({
    "Nome": ["Ana", "Luis", "Betania", "Carlos", "Lucia"],
    'Cidade': ['São Paulo', np.nan, 'São Paulo', np.nan, 'Campos do Jordão']
})
df_cidades['cidade_preenchida'] = df_cidades['Cidade'].fillna('Não informado')
df_cidades

df_limpo = df.dropna()

df_limpo.isnull().sum()

df_limpo.head()

df_limpo.info()

df_limpo = df_limpo.assign(work_year = df_limpo['work_year'].astype('int64'))

df_limpo.head()

df_limpo('experience_level').value_counts().plot(kind='bar', title='Tipo de experiencia')

import seaborn as sns

sns.barplot(data = df_limpo, x = 'experience_level' , y = 'salary_in_usd')

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.barplot(data=df_limpo, x='experience_level', y='salary_in_usd')
plt.title('Distribuição de Salários por Nível de Experiência')
plt.xlabel('Nível de Experiência')
plt.ylabel('Salário médio anual (USD)')
plt.show()

df_limpo.groupby('experience_level')['salary_in_usd'].mean().sort_values(ascending=False)

ordem = df_limpo.groupby('experience_level')['salary_in_usd'].mean().sort_values(ascending=True).index
ordem

plt.figure(figsize=(10, 6))
sns.barplot(data=df_limpo, x='experience_level', y='salary_in_usd', order = ordem)
plt.title('Distribuição de Salários por Nível de Experiência')
plt.xlabel('Nível de Experiência')
plt.ylabel('Salário médio anual (USD)')
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(df_limpo['salary_in_usd'], bins = 50, kde=True)
plt.title('Distribuição de Salários Anuais')
plt.xlabel('Salário em USD')
plt.ylabel('Frequência')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(x= df_limpo ['salary_in_usd'])
plt.title('Boxplot Salário')
plt.xlabel('Salário em USD')
plt.show()

ordem_experiencias = ['EN', 'MI', 'SE', 'EX']
labels = ['Junior', 'Pleno', 'Senior', 'Executivo']

plt.figure(figsize=(10, 5))
sns.boxplot(x= 'experience_level', y= 'salary_in_usd', data=df_limpo, order=ordem_experiencias)
plt.title('Distribuição de Salários por Nível de Experiência')
plt.xlabel('Nível de Experiência')
plt.ylabel('Salário em USD')
plt.xticks(ticks=range(len(ordem_experiencias)), labels=labels)
plt.show()

ordem_experiencias = ['EN', 'MI', 'SE', 'EX']
labels = ['Junior', 'Pleno', 'Senior', 'Executivo']

plt.figure(figsize=(10, 5))
sns.boxplot(x= 'experience_level', y= 'salary_in_usd', data=df_limpo, order=ordem_experiencias, palette='Set2', hue='experience_level')
plt.title('Distribuição de Salários por Nível de Experiência')
plt.xlabel('Nível de Experiência')
plt.ylabel('Salário em USD')
plt.xticks(ticks=range(len(ordem_experiencias)), labels=labels)
plt.show()

import plotly.express as px

df_agg = df_limpo.groupby('experience_level')['salary_in_usd'].mean().sort_values(ascending=False).reset_index()

ordem_experiencias = ['EN', 'MI', 'SE', 'EX']
labels = ['Junior', 'Pleno', 'Senior', 'Executivo']

fig = px.bar(df_agg, x='experience_level', y='salary_in_usd',
             title='Média Salarial por Nível de Experiência (Plotly)',
             labels={'experience_level': 'Nível de Experiência', 'salary_in_usd': 'Média Salarial (USD)'},
             category_orders={'experience_level': ordem_experiencias})

fig.update_layout(xaxis = dict(tickmode = 'array', tickvals = ordem_experiencias, ticktext = labels))

fig.show()

remoto_contagem = df_limpo['remote_ratio'].value_counts().reset_index()
remoto_contagem.columns = ['employment_type', 'count']
remoto_contagem

fig = px.pie(remoto_contagem,
             names= 'employment_type',
             values='count',
             title='Proporção dos tipode de trabalho'
             )

fig.show()

remoto_contagem = df_limpo['remote_ratio'].value_counts().reset_index()
remoto_contagem.columns = ['employment_type', 'count']
remoto_contagem

fig = px.pie(remoto_contagem,
             names= 'employment_type',
             values='count',
             title='Proporção dos tipos de de trabalho',
             hole=0.3
             )

fig.update_traces(textinfo='percent+label')
fig.show()

df.head()

pip install pycountry

import pycountry

def iso2_to_iso3(code):
  try:
    return pycountry.countries.get(alpha_2=code).alpha_3
  except:
    return None

df_limpo['employee_residence'] = df_limpo['employee_residence'].apply(iso2_to_iso3)

df_ds = df_limpo[df_limpo['job_title'].str.contains('Data Scientist')]
media_ds_pais = df_ds.groupby('employee_residence')['salary_in_usd'].mean().reset_index()

fig = px.choropleth(media_ds_pais,
                    locations= 'employee_residence',
                    color= 'salary_in_usd',
                    color_continuous_scale= 'rdylgn',
                    title= 'Média Salarial por País (Data Scientist)',
                    labels= {'employee_residence': 'País', 'salary_in_usd': 'Média Salarial (USD)'}
                    )

fig.show()

df_limpo.head()

df_limpo.to_csv('df_limpo.csv', index=False)